### ISSUE TITLE
How to run the examples

### ISSUE THREAD

**Issue by EteimZ** [aper-dev/aper#26]
I'm currently trying to run the drop-four example but its not working.

I ran the following command
```bash
cargo build
```
It built successfully then I ran 
```bash
cargo run -p drop-four-client
```
This return an error:

```bash
error: a bin target must be available for `cargo run`
```
I'm currently stuck and I would really love to try out the examples.

**Comment by paulgb** [comment]
Hi Youdiowei, good question, this isn't currently well documented. I've added a note about how to run them using [Jamsocket](https://github.com/drifting-in-space/jamsocket). I wish there was a way to build multiple targets with `cargo` directly, but currently there is not.

**Comment by paulgb** [comment]
Here is the note I added: https://github.com/drifting-in-space/aper/blob/main/examples/README.md
